version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fasttech-network

  products-api-read:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-api-read
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongo:27017/FastTechFoods-ProductsDB
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - mongo
    networks:
      - fasttech-network

volumes:
  mongo_data:

networks:
  fasttech-network: